server:
  port: 8080

app:
  name: quastio
  version: 0.1.1
  thread-count: 3

search:
  percent-ignore-lemmas-too-match-found: 95

spring:
  datasource:
    username: user
    password: pass
    url: jdbc:mysql://localhost:3306/search_engine?useSSL-false&requireSSL=false&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    #properties:
      #hibernate:
        #dialect: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: validate
    show-sql: true
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.xml

jsoup-settings:
  user-agent: QuastioSearchBot
  #user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/143.0.0.0 Safari/537.36
  referrer: http://www.google.com

indexing-settings:
  sites:
    #- url: https://www.lenta.ru/
    #  name: Лента.ру
    #- url: https://www.skillbox.ru/
    #  name: Skillbox
    #- url: https://www.playback.ru/
    #  name: PlayBack.Ru
    #- url: https://volochek.life/
    #  name: Volochek
    #- url: http://radiomv.ru/
    #  name: Radiomv
    #- url: https://ipfran.ru/
    #  name: Ipfran
    #- url: https://dimonvideo.ru/
    #  name: Dimonvideo
    - url: https://nikoartgallery.com/
      name: Nikoartgallery
    #- url: https://et-cetera.ru/mobile/
    #  name: Et-cetera
    #- url: https://www.lutherancathedral.ru/
    #  name: Lutherancathedral
    #- url: https://dombulgakova.ru/
    #  name: Dombulgakova
    #- url: https://www.svetlovka.ru/
    #  name: Svetlovka
    - url: https://sendel.ru/
      name: Sendel
    #- url: https://fakeandnotexist.ru
    #  name: fakeandnotexist